let all=[],filtered=[],markers=L.layerGroup(),map,deferredPrompt;const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function init(){all=await fetch('data/installations.json').then(r=>r.json());map=L.map('map',{zoomControl:true}).setView([28.35,-15.9],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);markers.addTo(map);bind();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js')}
function bind(){$('#search').addEventListener('input',render);$('#tech').addEventListener('change',render);$('#source').addEventListener('change',render);$('#fit').onclick=()=>map.setView([28.35,-15.9],7);$('#closeDetail').onclick=closeDetail;document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#source').value=b.dataset.view==='pending'?'unmapped':'';render()});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=()=>deferredPrompt?.prompt();$('#excelFile').addEventListener('change',importExcel)}
function render(){const q=$('#search').value.trim().toLowerCase(),tech=$('#tech').value,src=$('#source').value;filtered=all.filter(x=>{const hay=[x.installation,x.client,x.address,x.model,x.order,x.machine,x.zone].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!tech||String(x.technician).toUpperCase()===tech)&&(!src||(src==='mapped'?x.lat!=null:x.lat==null))});stats();list();drawMarkers()}
function stats(){const mapped=all.filter(x=>x.lat!=null).length,pending=all.length-mapped,ol=all.filter(x=>String(x.technician).toUpperCase()==='OLIVER').length,be=all.filter(x=>String(x.technician).toUpperCase()==='BERNARDO').length;$('#stats').innerHTML=[[all.length,'Total'],[mapped,'En el mapa'],[pending,'Sin ubicar'],[ol+be,'Oliver + Bernardo']].map(x=>`<div class="stat"><b>${x[0].toLocaleString('es-ES')}</b><span>${x[1]}</span></div>`).join('')}
function list(){$('#resultCount').textContent=`${filtered.length.toLocaleString('es-ES')} instalaciones`;$('#list').innerHTML=filtered.slice(0,500).map((x,i)=>`<article class="item" data-id="${esc(x.id)}"><h3>${x.installation?'ID '+esc(x.installation):'Sin código'} · ${esc(x.client||x.address||'Instalación')}</h3><p>${esc(x.address||'Dirección no incluida')}</p><p><span class="badge">${esc(x.model||'Modelo sin indicar')}</span>${x.technician?`<span class="badge">${esc(x.technician)}</span>`:''}${x.lat==null?'<span class="badge pending">Pendiente de ubicar</span>':''}</p></article>`).join('')||'<div class="detail">No hay resultados.</div>';document.querySelectorAll('.item').forEach(el=>el.onclick=()=>show(all.find(x=>x.id===el.dataset.id)))}
function drawMarkers(){markers.clearLayers();filtered.filter(x=>x.lat!=null).slice(0,3000).forEach(x=>{const m=L.circleMarker([x.lat,x.lng],{radius:5,weight:1,fillOpacity:.8});m.bindTooltip(`${x.installation?'ID '+x.installation:'Instalación'} · ${x.client||x.address||''}`);m.on('click',()=>show(x));m.addTo(markers)})}
function show(x){$('#detail').hidden=false;$('#list').hidden=true;$('#closeDetail').hidden=false;const nav=x.lat!=null?`https://www.google.com/maps/dir/?api=1&destination=${x.lat},${x.lng}`:'';$('#detail').innerHTML=`<div class="detail"><h2>${x.installation?'ID '+esc(x.installation):'Instalación'}</h2><dl>${[['Cliente',x.client],['Dirección',x.address],['Modelo',x.model],['Técnico',x.technician],['Pedido',x.order],['Nº máquina',x.machine],['Fecha pedido',x.orderDate],['Fecha montaje',x.installDate],['Zona',x.zone]].filter(a=>a[1]).map(a=>`<dt>${a[0]}</dt><dd>${esc(a[1])}</dd>`).join('')}</dl><div class="actions">${nav?`<a target="_blank" href="${nav}">Cómo llegar</a>`:''}<button id="editLocation">${x.lat==null?'Asignar ubicación':'Corregir ubicación'}</button></div><p><small>Las correcciones manuales se guardarán en el dispositivo y prevalecerán sobre futuras importaciones.</small></p></div>`;$('#editLocation').onclick=()=>alert('Editor de ubicación preparado para la siguiente versión: permitirá buscar dirección o tocar el mapa.');if(x.lat!=null)map.setView([x.lat,x.lng],16)}
function closeDetail(){$('#detail').hidden=true;$('#list').hidden=false;$('#closeDetail').hidden=true}
async function importExcel(e){const file=e.target.files[0];if(!file)return;try{const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:'array',cellDates:true}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});const selected=rows.filter(r=>['OLIVER','BERNARDO'].includes(String(r.COMERCIAL||'').trim().toUpperCase()));alert(`Excel leído correctamente.
${rows.length} filas totales.
${selected.length} de Oliver o Bernardo.

En la siguiente fase activaremos la fusión permanente y el informe previo de cambios.`)}catch(err){alert('No se pudo leer el Excel: '+err.message)}finally{e.target.value=''}}
init();