let base=[],all=[],filtered=[],markers=L.layerGroup(),map,deferredPrompt,current=null,pickMode=false,tempMarker=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STORE='ca-mapa-overrides-v2', STYLE='ca-mapa-styles-v2';
const defaults={size:6,kml:{color:'#2f80ed',shape:'circle'},OLIVER:{color:'#f2994a',shape:'square'},BERNARDO:{color:'#9b51e0',shape:'diamond'},unmapped:{color:'#9aa8b6',shape:'circle'}};
let styles=loadStyles();
function loadStyles(){try{return {...defaults,...JSON.parse(localStorage.getItem(STYLE)||'{}')}}catch{return structuredClone(defaults)}}
function overrides(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}}
function saveOverride(id,patch){const o=overrides();o[id]={...(o[id]||{}),...patch,updatedAt:new Date().toISOString()};localStorage.setItem(STORE,JSON.stringify(o));mergeData()}
function mergeData(){const o=overrides();all=base.map(x=>({...x,...(o[x.id]||{})}));render()}
async function init(){base=await fetch('data/installations.json').then(r=>r.json());mergeData();map=L.map('map',{zoomControl:true}).setView([28.35,-15.9],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);markers.addTo(map);bind();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js')}
function bind(){
 $('#search').addEventListener('input',render);$('#tech').addEventListener('change',render);$('#source').addEventListener('change',render);$('#fit').onclick=()=>map.setView([28.35,-15.9],7);$('#closeDetail').onclick=closeDetail;$('#styleBtn').onclick=openStyles;
 $$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).hidden=true);
 $$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#source').value=b.dataset.view==='pending'?'unmapped':'';render()});
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=()=>deferredPrompt?.prompt();$('#excelFile').addEventListener('change',importExcel);
 $('#pointSize').addEventListener('input',()=>{styles.size=Number($('#pointSize').value);saveStyles()});$('#resetStyles').onclick=()=>{styles=structuredClone(defaults);saveStyles();openStyles()};
 $('#saveLocation').onclick=saveLocation;$('#cancelLocation').onclick=closeLocation;
 map.on('click',e=>{if(!pickMode)return;$('#editLat').value=e.latlng.lat.toFixed(7);$('#editLng').value=e.latlng.lng.toFixed(7);$('#pickStatus').textContent='Punto seleccionado en el mapa.';if(tempMarker)map.removeLayer(tempMarker);tempMarker=L.marker(e.latlng).addTo(map)});
}
function render(){if(!all.length)return;const q=$('#search').value.trim().toLowerCase(),tech=$('#tech').value,src=$('#source').value;filtered=all.filter(x=>{const hay=[x.installation,x.client,x.address,x.model,x.order,x.machine,x.zone,x.comments,x.maintenance].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!tech||String(x.technician).toUpperCase()===tech)&&(!src||(src==='mapped'?x.lat!=null:x.lat==null))});stats();list();drawMarkers();notice()}
function stats(){const mapped=all.filter(x=>x.lat!=null).length,pending=all.length-mapped,ol=all.filter(x=>x.technician==='OLIVER').length,be=all.filter(x=>x.technician==='BERNARDO').length;$('#stats').innerHTML=[[all.length,'Total'],[mapped,'En el mapa'],[pending,'Sin ubicar'],[ol+be,'Oliver + Bernardo']].map(x=>`<div class="stat"><b>${x[0].toLocaleString('es-ES')}</b><span>${x[1]}</span></div>`).join('')}
function notice(){const tech=$('#tech').value,mapped=filtered.filter(x=>x.lat!=null).length,n=$('#notice');if(tech&&mapped===0&&filtered.length){n.hidden=false;n.innerHTML=`<b>${tech}: ${filtered.length} instalaciones encontradas, pero ninguna tiene coordenadas.</b><br>Ábrelas desde el listado y pulsa <em>Asignar ubicación</em>. En cuanto guardes el punto, aparecerá en el mapa.`}else n.hidden=true}
function list(){const mapped=filtered.filter(x=>x.lat!=null).length;$('#resultCount').textContent=`${filtered.length.toLocaleString('es-ES')} instalaciones · ${mapped.toLocaleString('es-ES')} en mapa`;$('#list').innerHTML=filtered.slice(0,700).map(x=>`<article class="item" data-id="${esc(x.id)}"><div class="item-top"><h3>${x.installation?'ID '+esc(x.installation):'Sin código'} · ${esc(x.client||x.address||'Instalación')}</h3><span class="dot" style="background:${markerStyle(x).color}"></span></div><p>${esc(x.address||'Dirección no incluida')}</p><p><span class="badge">${esc(x.model||'Modelo sin indicar')}</span>${x.technician?`<span class="badge">${esc(x.technician)}</span>`:''}${x.lat==null?'<span class="badge pending">Pendiente de ubicar</span>':''}</p></article>`).join('')||'<div class="detail">No hay resultados.</div>';$$('.item').forEach(el=>el.onclick=()=>show(all.find(x=>x.id===el.dataset.id)))}
function markerStyle(x){if(x.customColor)return {color:x.customColor,shape:x.customShape||'circle'};if(x.technician==='OLIVER')return styles.OLIVER;if(x.technician==='BERNARDO')return styles.BERNARDO;return styles.kml}
function iconFor(x){const st=markerStyle(x),s=styles.size||6,shape=x.customShape||st.shape||'circle';let transform='';if(shape==='diamond')transform='transform:rotate(45deg)';const radius=shape==='circle'?'50%':'3px';return L.divIcon({className:'custom-marker',html:`<span style="width:${s*2}px;height:${s*2}px;background:${st.color};border-radius:${radius};${transform}"></span>`,iconSize:[s*2+4,s*2+4],iconAnchor:[s+2,s+2]})}
function drawMarkers(){markers.clearLayers();filtered.filter(x=>x.lat!=null).slice(0,4000).forEach(x=>{const m=L.marker([x.lat,x.lng],{icon:iconFor(x)});m.bindTooltip(`${x.installation?'ID '+x.installation:'Instalación'} · ${x.client||x.address||''}`);m.on('click',()=>show(x));m.addTo(markers)})}
function field(label,value){return value!==''&&value!=null?`<dt>${label}</dt><dd>${esc(value)}</dd>`:''}
function show(x){current=x;$('#detail').hidden=false;$('#list').hidden=true;$('#closeDetail').hidden=false;const nav=x.lat!=null?`https://www.google.com/maps/dir/?api=1&destination=${x.lat},${x.lng}`:'';const st=markerStyle(x);$('#detail').innerHTML=`<div class="detail"><div class="title-row"><div><small>${x.source==='excel'?'PEDIDO 2026':'REGISTRO HISTÓRICO'}</small><h2>${x.installation?'ID '+esc(x.installation):'Instalación'}</h2></div><span class="large-dot" style="background:${st.color}"></span></div><dl>${field('Cliente',x.client)}${field('Dirección',x.address)}${field('Modelo',x.model)}${field('Técnico',x.technician)}${field('Mantenimiento',x.maintenance)}${field('Pedido',x.order)}${field('Nº máquina',x.machine)}${field('Fecha pedido',x.orderDate)}${field('Pedido a fábrica',x.factoryOrderDate)}${field('Aprobación',x.approvalDate)}${field('Salida fábrica',x.factoryExitDate)}${field('Fecha montaje',x.installDate)}${field('Taller',x.workshop)}${field('Zona',x.zone)}${field('Latitud',x.lat)}${field('Longitud',x.lng)}${field('Observaciones',x.comments||x.description)}</dl><div class="point-custom"><label>Color del punto<input id="customColor" type="color" value="${st.color}"></label><label>Forma<select id="customShape"><option value="circle">Círculo</option><option value="square">Cuadrado</option><option value="diamond">Rombo</option></select></label><button id="savePointStyle">Guardar estilo</button></div><div class="actions">${nav?`<a target="_blank" href="${nav}">Cómo llegar</a>`:''}<button id="editLocation">${x.lat==null?'Asignar ubicación':'Corregir ubicación'}</button></div><p><small>Los cambios manuales se guardan en este dispositivo y prevalecen sobre futuras importaciones.</small></p></div>`;$('#customShape').value=x.customShape||st.shape||'circle';$('#savePointStyle').onclick=()=>saveOverride(x.id,{customColor:$('#customColor').value,customShape:$('#customShape').value});$('#editLocation').onclick=()=>openLocation(x);if(x.lat!=null)map.setView([x.lat,x.lng],16)}
function closeDetail(){$('#detail').hidden=true;$('#list').hidden=false;$('#closeDetail').hidden=true;current=null}
function openStyles(){const defs=[['kml','Históricas'],['OLIVER','Oliver'],['BERNARDO','Bernardo']];$('#styleRows').innerHTML=defs.map(([k,n])=>`<div class="style-row"><strong>${n}</strong><input data-style="${k}" data-key="color" type="color" value="${styles[k].color}"><select data-style="${k}" data-key="shape"><option value="circle">Círculo</option><option value="square">Cuadrado</option><option value="diamond">Rombo</option></select></div>`).join('');$$('[data-style]').forEach(el=>{if(el.dataset.key==='shape')el.value=styles[el.dataset.style].shape;el.onchange=()=>{styles[el.dataset.style][el.dataset.key]=el.value;saveStyles()}});$('#pointSize').value=styles.size||6;$('#stylePanel').hidden=false}
function saveStyles(){localStorage.setItem(STYLE,JSON.stringify(styles));drawMarkers();list()}
function openLocation(x){current=x;pickMode=true;$('#locationPanel').hidden=false;$('#editAddress').value=x.address||'';$('#editLat').value=x.lat??'';$('#editLng').value=x.lng??'';$('#pickStatus').textContent='Desplaza el mapa y toca la ubicación exacta.';if(x.lat!=null){map.setView([x.lat,x.lng],17);tempMarker=L.marker([x.lat,x.lng]).addTo(map)}else{map.setView([28.35,-15.9],7)}}
function closeLocation(){pickMode=false;$('#locationPanel').hidden=true;if(tempMarker){map.removeLayer(tempMarker);tempMarker=null}}
function saveLocation(){if(!current)return;const lat=Number($('#editLat').value),lng=Number($('#editLng').value);if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat<27||lat>30||lng<-19||lng>-13){alert('Revisa las coordenadas. Deben corresponder a Canarias.');return}saveOverride(current.id,{lat,lng,address:$('#editAddress').value.trim()||current.address,zone:'Ubicación manual'});closeLocation();const updated=all.find(x=>x.id===current.id);show(updated)}
async function importExcel(e){const file=e.target.files[0];if(!file)return;try{const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:'array',cellDates:true}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:'',raw:true});const selected=rows.filter(r=>['OLIVER','BERNARDO'].includes(String(r.COMERCIAL||'').trim().toUpperCase()));alert(`Excel leído correctamente.\n${rows.length} filas totales.\n${selected.length} de Oliver o Bernardo.\n\nEsta versión conserva ubicaciones y estilos manuales. La fusión completa del Excel se activará en la siguiente actualización.`)}catch(err){alert('No se pudo leer el Excel: '+err.message)}finally{e.target.value=''}}
init();